# rubocop:disable all
# TODO - FIX COP
# rubocop:enable all

require:
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.4
  DisplayStyleGuide: false
  NewCops: enable
  Exclude:
    - 'backup/**/*'
    - 'build/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'db/*'
    - 'db/fixtures/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'
    - 'script/**/*'
    - 'Rakefile'
    - 'Gemfile'
    - 'Guardfile'
    - 'tmp.rb'
    - 'scratch.rb'

# Disable documentation cops
Documentation:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Metrics/ClassLength:
  Max: 180

Metrics/MethodLength:
  Max: 16

Layout/LineLength:
  Max: 180
  Exclude:
    - 'lib/tasks/*'

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/*'

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Enabled: false
