name: Auto Deployment to Github Pages

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@master

    - name: Install Ruby
      uses: actions/setup-ruby@v1
      with:
        version: 2.6.x
    - name: Ruby Version
      run: |
        ruby -v
    - name: Setup Ruby Dependencies
      run: |
        gem update bundler
        bundle install --jobs 4 --retry 3
    - name: Test Ruby Dependencies
      run: |
        bundle exec rake -T