name: Deployment to Github Pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v1.1.0
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./build
