name: Deploy Static Site

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # - uses: ./.github/workflows/build

      - run: echo "Running Deploy Static Site"
        if: github.event.pull_request.merged == true

    # - name: Deploy to Github Pages
    #   uses: peaceiris/actions-gh-pages@v1.1.0
    #   if: success()
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    #     PUBLISH_BRANCH: gh-pages
    #     PUBLISH_DIR: ./build
