name: Update GitHub Pages on Merge to Master

on:
  pull_request:
    branches:
    - master

jobs:
  deploy:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:
    - uses: actions/test-website-build@master
    - run: echo "Running Update GitHub Pages on Merge to Master"

    # - name: Deploy to Github Pages
    #   uses: peaceiris/actions-gh-pages@v1.1.0
    #   if: success()
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    #     PUBLISH_BRANCH: gh-pages
    #     PUBLISH_DIR: ./build
